import type { FC } from "hono/jsx";

export type HtmlContentProps = {
	html: string;
};

export const HtmlInline: FC<HtmlContentProps> = ({ html }) => {
	return (
		<span
			// biome-ignore lint/security/noDangerouslySetInnerHtml: Displaying HTML generated by typst-docs.
			dangerouslySetInnerHTML={{ __html: html }}
		/>
	);
};
