import type { FC } from "hono/jsx";
import { twMerge } from "tailwind-merge";

export type HtmlContentProps = {
	html: string;
};

export const HtmlBlock: FC<HtmlContentProps> = ({ html }) => {
	return (
		<div
			class={twMerge([
				"overflow-hidden",
				// Move the margin for inner `<p>`s to the outer `<div>`, making it collapsible with sibling `<div>`s.
				"mt-5",
				"[&_p]:first:mt-0",
				"mb-5",
				"[&_p]:last:mb-0",
				"[&_img]:mx-auto",
				"[&_img]:block",
				"[&_img]:max-w-full",
				"[&_img]:h-auto",
				"[&_img]:object-contain",
				"[&_img]:w-auto",
				"[&_pre]:overflow-x-auto",
				"[&_pre]:max-w-full",
				"[&_pre]:whitespace-pre",
				"[&_pre]:break-all",
				"[&_pre_code]:block",
				"[&_pre_code]:w-full",
			])}
			// biome-ignore lint/security/noDangerouslySetInnerHtml: Displaying HTML generated by typst-docs.
			dangerouslySetInnerHTML={{ __html: html }}
		/>
	);
};
